baseURL: "https://getinsurancesmart.com"
languageCode: "en-us"
title: "InsuranceSmart"

params:
    cloudinary_url: "https://res.cloudinary.com/modii/"

menu:
    shop_menu:
    - identifier: Column 1
      name: Column 1
      - identifier: life
        name: Life
        parent: Column 1
        post: '<i class="fas fa-heartbeat"></i>'
      - identifier: health
        name: Health
        post: '<i class="fas fa-notes-medical"></i>'
        parent: Column 1
    - identifier: column-2
      name: Column 2
      - identifier: auto
        name: Personal Auto & Vehicle
        post: '<i class="fas fa-car"></i>'
        parent: Column 2
    - identifier: column-3
      name: Column 3
      - identifier: home
        name: Personal Property
        post: '<i class="fas fa-home"></i>'
        parent: Column 3
      - identifier: umbrella
        name: Umbrella Insurance
        post: '<i class="fas fa-umbrella"></i>'
        parent: Column 3


