baseURL = "https://getinsurancesmart.com"
enableRobotsTXT = true
languageCode = "en-us"
title = "InsuranceSmart"
[params]
cloudinary_url = "https://res.cloudinary.com/modii/"
[taxonomies]
category = "categories"
tag = "tags"
