baseURL = "https://getinsurancesmart.com"
languageCode = "en-us"
title = "InsuranceSmart"

[params]
cloudinary_url = "https://res.cloudinary.com/modii/"

[[menu.shop_menu]]
identifier = "column-3"
name = "Column 3"
weight = 3
[[menu.shop_menu]]
identifier = "column-2"
name = "Column 2"
weight = 2
[[menu.shop_menu]]
identifier = "column-1"
name = "Column 1"
weight = 1

[[menu.explore]]
name = "About Us"
weight = 1
[[menu.explore]]
name = "Testimonials"
URL = "/testimonies/"
weight = 2
[[menu.explore]]
name = "Contact"
weight = 3
URL = "#"