---
new_page_extension: md
auto_deploy: false
admin_path: "/elhefe"
webhook_url: 
sections:
- path: content/products
  label: Products
  create: all
  templates:
  - product
- path: content/insurancecategories
  label: Product Categories
  create: all
  templates:
  - product-category
- path: content/posts
  label: Posts
  create: all
  templates:
  - article
- path: content/testimonies
  label: Testimonies
  create: all
- path: content/staff
  label: Staff
  create: all
  templates:
  - staff
- path: content
  label: Homepage
  create: none
upload_dir: insurancesmart
public_path: https://res.cloudinary.com/modii
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
version: 0.42.2
