---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: content/_index.md
  label: Homepage
  match: "**/*"
- type: directory
  path: content/products
  label: Products
  create: all
  match: "**/*"
  exclude: "**/_index.md"
  templates:
  - product
- type: directory
  path: content/insurancecategories
  label: Product Categories
  create: all
  match: "**/*"
  templates:
  - product-category
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - article
- type: directory
  path: content/testimonies
  label: Testimonies
  create: all
  match: "**/*"
  templates:
  - testimony
- type: directory
  path: content/staff
  label: Staff
  create: all
  match: "**/*"
  templates:
  - staff
- type: directory
  path: content
  label: Homepage
  create: none
  match: "*"
- type: heading
  label: Settings
- type: document
  path: data/general_settings.yaml
  label: General
- type: document
  path: data/menus.yaml
  label: Menus
upload_dir: insurancesmart
public_path: https://res.cloudinary.com/modii
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
version: '0.49'
