---
label: Product Category
hide_body: false
fields:
    - name: title
      label: Title
      type: text
      hidden: false
      default: ''
    - type: include
      name: seo
      label: SEO
      template: seo
    - name: subheading
      label: Subheading
      type: text
      hidden: false
      default: ''
    - type: blocks
      name: quote
      label: Quote Form
      template_types:
          - quoteit-quote-form
          - unitedhealthcare-quote-form
          - safeco-quote-form
          - call-for-a-quote
          - custom-link
      description: Quote form for customers to fill out
    - type: file
      name: featured_image
      label: Banner Image
      description: Banner image to appear on category page
    - type: number
      name: weight
      label: Category Weight
      description: Decides priority in category lists. (I.E. 1 will be listed before 5)
      config:
          step: '1'
          required: true
      default: '5'
    - type: text
      name: fa_icon
      label: Font Awesome Icon
      description:
          Icon name for this category (Uses the font awesome icon library found
          at https://fontawesome.com/icons)
pages:
    - content/insurancecategories/health.md
    - content/insurancecategories/life.md
    - content/insurancecategories/medicare.md
    - content/insurancecategories/other.md
    - content/insurancecategories/property.md
