---
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- type: include
  template: seo
  label: SEO
  name: seo
- type: file
  name: featured_image
  label: Banner Image
  description: Large image to be featured on the page.
- type: text
  name: description
  label: Short Description
  description: This is a short description that will appear at the top of the page
  config:
    required: true
- type: blocks
  name: quote
  label: Quote Block
  template_types:
  - safeco-quote-form
  description: Choose what quote form to display on this page. You want to choose
    whichever one is relevant to the product. (Only the first item in the list will
    be displayed)
- type: field_group_list
  name: faqs
  label: Frequently Asked Questions
  fields:
  - type: text
    name: question
    label: Question
    config:
      required: true
  - type: textarea
    name: answer
    label: Answer
    config:
      required: true
      wysiwyg: true
      schema:
        format: markdown
  config:
    labelField: question
- type: blocks
  name: resources
  label: Resources
  description: If you have any additional resources regarding the product (i.e. brochures,
    graphs, images, information websites) you can upload/link them here.
  template_types:
  - resource-external-link
  - resource-document-image
- type: textarea
  name: mikes_take
  label: Mike's Take
  description: Product advice from the InsuranceSmart founding
  config:
    wysiwyg: true
    schema:
      format: markdown
- type: select
  name: recommended_articles
  config:
    source:
      type: simple
    required: true
    options:
    - choose automatically
    - let me choose
  label: Recommended Articles
  default: choose automatically
- type: list
  name: custom_article_list
  label: Article Selection
  description: Manually select the articles you want to feature (must select "let
    me choose" above for these articles to display.
  config:
    use_select: true
    source:
      type: pages
pages:
- content/products/home/home.md
- content/products/health/health-protectorguard.md
- content/products/auto/personal-auto.md
- content/products/auto/boat.md
